name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy Laravel API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo_pgsql, pgsql, zip, bcmath, opcache, gd, intl

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --no-progress

      - name: Deploy Backend via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSKEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./"
          target: ${{ secrets.SFTP_BACKEND_PATH }}
          overwrite: true
          rm: false
          exclude: |
            .git*
            node_modules
            tests
            storage/logs/*
            storage/framework/cache/*
            storage/framework/sessions/*
            storage/framework/views/*
            .github
            *.env
            *.md
            Dockerfile*
            docker-compose*
            docker-entrypoint*
            supervisord*
            nginx.conf*

      - name: Run Remote Commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSKEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SFTP_BACKEND_PATH }}
            PHP_CLI=/usr/local/bin/php
            $PHP_CLI artisan down || true
            $PHP_CLI artisan migrate --force
            $PHP_CLI artisan optimize:clear
            $PHP_CLI artisan config:cache
            $PHP_CLI artisan route:cache
            $PHP_CLI artisan up
